### ISSUE TITLE
Re-write of front-end in PureScript

### ISSUE THREAD

**Issue by sectore** [aelve/guide#164]
by building an isomorphic approach.

**Comment by neongreen** [comment]
This will not happen, the main reason being that neither me nor @vrom911 managed to get productive with PureScript. I'd rather go for something more mainstream, even if I have to sacrifice isomorphism and some type-safety along the way.

**Comment by sectore** [comment]
@neongreen Would be [Miso](https://haskell-miso.org/) still an option for you (as discussed earlier this year in :portugal:)?

**Comment by neongreen** [comment]
Frankly, I managed to forget the Mido discussion :/ But the ship has sailed
already – I have gathered a team to do this in Vue+TypeScript.

I don't have experience one way or another, so I'm actually curious to see
whether we'll stumble upon any significant pitfalls with Vue. I might also
try GHCJS for a different project in the future! Especially if I see that
Vue turned out to be a bad choice :)
