### ISSUE TITLE
Page loading takes forever on Firefox

### ISSUE THREAD

**Issue by mrkkrp** [aelve/guide#24]
Not sure why, [this page](https://guide.aelve.com/haskell) takes about 10 seconds to load (no, I have a fast connection). I have noticed that as development of the service progresses, it's taking longer and longer, I'm curious why it is so. Can you reproduce the problem? I have several plugins turned on and I thought it may have something to do with the plugins, but even if I turn them off the problem persists.

**Comment by neongreen** [comment]
I can reproduce the problem, yeah. It could be [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=543494) – when I remove all `<textarea>`s, the page loads much faster. On the other hand, when I remove `autosize.js` the page loads faster too – maybe they both are the culprit? At any rate, I guess I'll have to start generating textareas on the fly (which is something I really wanted to avoid). I'll look into this later.

> as development of the service progresses, it's taking longer and longer

I think that's because I keep adding content, not because of code itself.

**Comment by neongreen** [comment]
It should be somewhat better now. `/haskell` is still slow to load, but category pages are reasonably fast, and since the “all categories in one” page is going to be removed at some point, it's not a big issue. However, I'm still planning to start generating more elements dynamically – so, leaving this open.

**Comment by neongreen** [comment]
> planning to start generating more elements dynamically

Or not. Generating things dynamically is a pain, so I'm only going to do it if it's needed.
