### ISSUE TITLE
Looks ugly in mobile Chrome

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#9]
**Update:** new set of woes:
- [x] There are no margins for anything-that-is-not-inside-items
- [x] Icons break their containers when the name of the item is long
- [x] There's an ugly right margin
- [x] Should list cons after pros on mobile, not side-to-side

---

Original problems (fixed in the referenced commit):
- The icons don't scale with the text
- Left/right margins are too wide
- Bullets in pros/cons touch the borders
- Line height is too small
- Code doesn't scale at all

**Comment by neongreen** [comment]
A new set of woes:

  * [ ] There are no margins for anything-that-is-not-inside-items
  * [ ] Icons break their containers when the name of the item is long
  * [ ] There's an ugly right margin

**Comment by mrkkrp** [comment]
How about using Bootstrap or another framework that is built with mobile in mind? That would certainly imporve look and feel (although as I understand you want to create custom styling and without heavy artillery). On related note, some spacing around “search” input box would be great. And buttons to add things and search for them (it's of course intuitive that you should press <kbd>↵ Enter</kbd> to execute action, but it really looks like something is missing, because this sort of field is always accompanied by a button).

**Comment by neongreen** [comment]
> And buttons to add things and search for them

Will do. (And for pros/cons I might also add some text like “press Enter to save” because I'm afraid that with a button it wouldn't be obvious that you can do that.)

> How about using Bootstrap or another framework that is built with mobile in mind?

Well, it feels like fixing layout manually could be easier than learning a framework (especially since most of my problems are caused by “I have no idea what I'm doing” rather than anything else). If it turns out that after I finish it *still* sucks, I'll look at Bootstrap, sure.
